<?php
namespace app\dtalk\controller;

use think\App;
use think\View;
use app\BaseController;

class Base extends BaseController {
    //公钥  用户登录验证
    public $key = 'c4ca4238a0b923820dcc509a6f75849b' ;
    //私钥  数据加密
    public $secret = '28c8edde3d61a0411511d3b1866f0636'  ;
    protected $request;
    //默认分页条数
    protected $limit = 10;
    protected $_data = [];
    protected $_error = [
        '200' => '数据操作成功！',
        '201' => '未知错误！',
        '202' => '参数缺失！',
        '203' => '数据操作失败！',
        '205' => '记录不存在或已删除！',

        '501' => '验证码不存在或已失效！',
        '502' => '验证码错误！',
        '503' => '密码不合法！',
        '504' => '两次密码不一致！',
        '505' => '当前用户已冻结，请联系管理员解封！',
        '506' => '未填写密码！',

        '1000' => '操作失败，请核对数据！',
        '1001' => '参数缺失！',

        '1002' => '验证码错误或超时！',
        '1017' => '未填写验证码！',

        '1003' => '登录失败！',

        '1004' => '手机号不合法',
        '1005' => '用户不存在',
        '1006' => '账号或密码错误',
        '1007' => '该账号被禁用',

        '1008' => '请输入昵称',
        '1009' => '您输入的用户昵称已存在，请重新输入！',
        '1015' => '用户个人介绍不能超过30字！',
        '1016' => '用户昵称不能超过20字！',
        '1018' => '昵称已存在，请重新输入！',
        '1019' => '昵称不合法(数字、字母或组合)！',

        '1010' => '请输入工号！',
        '1011' => '工号错误！',

        '1012' => '您不是内部员工（手机号不匹配）！',
        '1013' => '身份证错误或不合法！',
        '1014' => '请输入手机号！',
        '1020' => '您还不是作者不能发布文章！',
        //关注 收藏
        '1030' => '不能关注本身文章',
        '1031' => '不能收藏本身文章',
        '1032' => '不能点赞本身文章',

        '2000' => '当前文章不存在或已删除',
        '2001' => '文章标题不能为空',
        '2002' => '文章标题限定5-30字',
        '2003' => '请选择文章分类',
        '2004' => '文章内容不能为空',
        '2005' => '文章字数100字以上',
        '2006' => '请上传视频',
        '2007' => '当前文章审核中，禁止编辑',

        '2008' => '未发起或已删除审核申请',
        '2009' => '审核流程已结束',
        '2010' => '审核用户不存在或已更改',
        '2011' => '你不是审核用户，不能审核',
        '2012' => '当前驳回审核已撤销',
        '2013' => '您不能撤回该驳回记录',
        '2014' => '您已审核过',
        '2015' => '审核用户不存在或已更改',
        '2016' => '未配置审核人员',

        '2050' => '标签不能超过3个',


        '300' => 'token不存在',
        '301' => '用户未登录',
        '302' => 'token在黑名单中',
        '299' => 'token已过期',
        '298' => 'token已过期,无法再次刷新',
        '297' => '发布时间（iat）不能大于当前时间',
    ] ;
    public function __construct(App $app, View $view)
    {
        parent::__construct($app, $view);
        $this->app     = $app;
        $this->request = $this->app->request;
        $this->view = $view;
    }
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * Commit:发送验证码
     * Function: sendSms
     * User: stars<1014916675@qq.com>
     * DateTime: 2019-11-26 17:36:27
     * @Return \think\response\Json
     */
    public function sendSms()
    {
        return parent::sendSms(); // TODO: Change the autogenerated stub
    }
    /**
     * Commit:验证验证码
     * Function: checkSms
     * User: stars<1014916675@qq.com>
     * DateTime: 2019-11-26 17:48:00
     * @Return bool|\think\response\Json
     */
    public function checkSms()
    {
        return parent::checkSms(); // TODO: Change the autogenerated stub
    }
    public function returnAjax($code = 200, $data = [], $msg = '')
    {
        return parent::returnAjax($code, $data, $msg); // TODO: Change the autogenerated stub
    }

    /**
     * Commit: 图片上传
     * Function: upload
     * @Param string $filedir 文件存放目录
     * @Param string $field 上传字段名
     * @Param bool $type true false
     * User: stars<1014916675@qq.com>
     * DateTime: 2019-11-29 09:48:51
     * @Return \think\response\Json
     */
    public function upload($filedir = 'article', $field = 'file', $type = false)
    {
        return parent::upload($filedir, $field, $type); // TODO: Change the autogenerated stub
    }

}